name: Build macOS Executable

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile Blackjack.py

    - name: Zip the executable
      run: zip -r blackjack_executable.zip dist/

    - name: Upload executable as artifact
      uses: actions/upload-artifact@v2
      with:
        name: blackjack_executable
        path: blackjack_executable.zip
